### ISSUE TITLE
Dependency resolution failed

### ISSUE THREAD

**Issue by Asrothear** [ripkens/SaltyChat-AltV#1]
[17:22:49] coreclr-module: version found: 3.0.0
[17:22:49] coreclr-module: version found: 3.1.4
[17:22:49] coreclr-module: version found: 5.0.0-preview.4.20251.6
[17:22:49] coreclr-module: greatest version: 5.0.0-preview.4.20251.6

Unhandled exception. System.InvalidOperationException: Dependency resolution failed for component W:\Test\LIVE_SERVER\resources\saltychat\SaltyChatServer.dll with error code -2147450734. Detailed error: Failed to locate managed application [W:\Test\LIVE_SERVER\resources\saltychat\SaltyChatServer.dll]

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at AltV.Net.Host.ResourceAssemblyLoadContext..ctor(String resourceDllPath, String resourcePath, String resourceName)
   at AltV.Net.Host.Host.ExecuteResource(IntPtr arg, Int32 argLength)

Getting this error while trying to test this

**Comment by Fynnoverse** [comment]
nevermind found it
